<?php

namespace Lit\BugReporter;

use Illuminate\Foundation\AliasLoader;
use Illuminate\Support\ServiceProvider;
use Lit\BugReporter\App\Facades\BugReportFacade;
use Lit\BugReporter\App\Services\BugReport;

class BugReporterServiceProvider extends ServiceProvider
{
    public function boot()
    {
        /** load views */
        $this->loadViewsFrom(__DIR__ . '/resources/views', 'bugreporter');

        /** publish file */
        $this->publishes([
            __DIR__ . '/resources/views' => base_path('resources/views/vendor/bugreporter'),
            __DIR__ . '/config/bugger.php' => config_path('luonglit/bugger.php')
        ]);

        $this->mergeConfigFrom(__DIR__ . '/config/bugger.php', 'luonglit.bugger');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        /** facades register */
        $this->app->bind('BugReport', BugReport::class);
        AliasLoader::getInstance()->alias('BuggerFa', BugReportFacade::class);
    }

}